name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Load secrets
        id: load-secrets
        uses: 1password/load-secrets-action@v1
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        with:
          load-env: |
            MY_SECRET=Development Credentials/Service Account Auth Token: GitHub Actions/credential

      - name: Test secret
        if: success()
        run: |
          echo "Testing secret access..."
          if [[ -n "$MY_SECRET" ]]; then
            echo "✓ Secret loaded successfully"
            echo "Testing 1Password CLI access..."
            op --version
            op vault list
          else
            echo "⨯ Failed to load secret"
            echo "Debug info:"
            echo "1Password CLI version: $(op --version)"
            echo "OP_MANAGED_VARIABLES: $OP_MANAGED_VARIABLES"
            exit 1
          fi
