name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
      
      - name: Load 1Password Secrets
        uses: 1password/load-secrets-action@v1
        with:
          # Export secrets to environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          # Reference secrets from vault
          SERVICE_ACCOUNT_TOKEN: op://Development Credentials/Service Account Auth Token: GitHub Actions/credential
          
      - name: Test 1Password Integration
        run: |
          if [ -n "$SERVICE_ACCOUNT_TOKEN" ]; then
            echo "✓ Successfully loaded 1Password service account token"
            # Test 1Password CLI
            op --version
            echo "✓ 1Password CLI is working"
          else
            echo "⨯ Failed to load 1Password service account token"
            exit 1
          fi
