name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Load secrets
        id: op-secrets # Give an ID to the step to access its outputs if needed
        uses: 1password/load-secrets-action@v2 # Ensure v2 is used
        with:
          export-env: true # Export the secret as an environment variable
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          # The variable on the left (LOADED_GITHUB_TOKEN) is how it will be named in the environment
          LOADED_GITHUB_TOKEN: "op://Development Credentials/Service Account Auth Token: GitHub Actions/credential"

      - name: Test secret access
        run: |
          echo "Checking loaded secret (LOADED_GITHUB_TOKEN)..."
          if [[ -n "$LOADED_GITHUB_TOKEN" ]]; then
            echo "✓ LOADED_GITHUB_TOKEN is populated."
            echo "Value starts with: ${LOADED_GITHUB_TOKEN:0:5}..." # GitHub will mask this
            
            echo "Testing GitHub API access with the loaded token..."
            # Use -Sfs to make curl silent on success but show errors
            if curl -Sfs -H "Authorization: token $LOADED_GITHUB_TOKEN" https://api.github.com/user > /dev/null; then
              echo "✓ GitHub token is valid and API call successful."
              echo "✓ Integration test passed."
            else
              echo "⨯ GitHub API call failed with the loaded token."
              exit 1
            fi
          else
            echo "⨯ Failed to load secret into LOADED_GITHUB_TOKEN."
            echo "Debug info:"
            echo "  1Password CLI version: $(op --version || echo 'op not found')"
            echo "  Checking OP_SERVICE_ACCOUNT_TOKEN presence (should be masked): ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN != '' }}"
            exit 1
          fi
