name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Load Secrets
        uses: 1password/load-secrets-action@v1
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        with:
          # List of secrets to load
          secrets: |
            SECRET_TOKEN = Development Credentials/Service Account Auth Token: GitHub Actions/credential

      - name: Test Loaded Secret
        shell: bash
        run: |
          if [[ -n "$SECRET_TOKEN" ]]; then
            echo "✓ Secret loaded successfully"
          else
            echo "⨯ Failed to load secret"
            exit 1
          fi
