name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
      
      - name: Load secret
        uses: 1password/load-secrets-action@v1
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          API_TOKEN: "op://Development Credentials/Service Account Auth Token: GitHub Actions/credential"
        with:
          export-env: true
            
      - name: Test secret
        env:
          # Reference the exported secret
          TOKEN: ${{ env.API_TOKEN }}
        run: |
          echo "Testing 1Password secret access..."
          if [[ -n "$TOKEN" ]]; then
            echo "✓ Secret loaded successfully"
            echo "✓ Integration test passed"
          else
            echo "⨯ Failed to load secret"
            exit 1
          fi
