name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Sign in to 1Password
        id: op-signin
        run: |
          echo "Signing in to 1Password..."
          if op signin --account brxperformance.1password.com; then
            echo "✓ Successfully signed in to 1Password"
            op vault list
          else
            echo "⨯ Failed to sign in to 1Password"
            exit 1
          fi

      - name: Load secrets
        if: success()
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
          secrets: |
            AUTH_TOKEN=op://Development Credentials/Service Account Auth Token: GitHub Actions/credential

      - name: Verify secrets
        if: success()
        run: |
          echo "Verifying secrets..."
          if [[ -n "$AUTH_TOKEN" ]]; then
            echo "✓ Secret loaded successfully"
            echo "✓ Integration test passed"
          else
            echo "⨯ Failed to load secret"
            echo "Debug information:"
            op --version
            op account list || true
            op vault list || true
            exit 1
          fi
