name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Load secret
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true # This is key for making it an env var
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          # Define the environment variable name and its 1Password reference
          # The variable name on the left (e.g., MY_SECRET_TOKEN) is what you'll use in subsequent steps
          MY_SECRET_TOKEN: "op://Development Credentials/Service Account Auth Token: GitHub Actions/credential"

      - name: Test secret access
        run: |
          echo "Checking loaded secret (MY_SECRET_TOKEN)..."
          if [[ -n "$MY_SECRET_TOKEN" ]]; then
            echo "✓ MY_SECRET_TOKEN is populated."
            echo "Value starts with: ${MY_SECRET_TOKEN:0:5}..." # GitHub will mask this
            
            echo "Testing GitHub API access with the loaded token..."
            if curl -Sfs -H "Authorization: token $MY_SECRET_TOKEN" https://api.github.com/user > /dev/null; then
              echo "✓ GitHub token is valid and API call successful."
              echo "✓ Integration test passed."
            else
              echo "⨯ GitHub API call failed with the loaded token."
              exit 1
            fi
          else
            echo "⨯ Failed to load secret into MY_SECRET_TOKEN."
            echo "Debug info:"
            echo "  1Password CLI version: $(op --version || echo 'op not found')"
            op vault list || true # Check if vault list works here (should with OP_SERVICE_ACCOUNT_TOKEN)
            exit 1
          fi
