name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Verify 1Password Access
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        run: |
          echo "Verifying 1Password access..."
          if op vault list --format=json; then
            echo "✓ Successfully accessed 1Password"
            echo "Available vaults:"
            op vault list
          else
            echo "⨯ Failed to access 1Password"
            exit 1
          fi

      - name: Load Secrets
        if: success()
        id: load-secrets
        uses: 1password/load-secrets-action@v1
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        with:
          load-env: false
          export-env: true
          secrets: |
            TEST_SECRET=op://Development Credentials/Service Account Auth Token: GitHub Actions/credential

      - name: Verify Secret
        if: success()
        run: |
          if [[ -n "$TEST_SECRET" ]]; then
            echo "✓ Secret loaded successfully"
            echo "✓ Integration test passed"
          else
            echo "⨯ Failed to load secret"
            echo "Available environment variables:"
            env | grep -v "TOKEN" | grep -v "SECRET"
            exit 1
          fi
