name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
      
      - name: Debug 1Password setup
        run: |
          echo "Checking 1Password CLI installation..."
          op --version
          echo "Verifying service account token..."
          if [ -n "${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}" ]; then
            echo "✓ Service account token is set"
          else
            echo "⨯ Service account token is missing"
          fi
      
      - name: Load secret
        id: op-secrets
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GITHUB_TOKEN: "op://Development Credentials/Service Account Auth Token: GitHub Actions/credential"
            
      - name: Test secret
        run: |
          echo "Testing 1Password secret access..."
          echo "Managed variables: $OP_MANAGED_VARIABLES"
          echo "Environment variables:"
          env | grep -v OP_SERVICE_ACCOUNT_TOKEN
          
          if [[ -n "$GITHUB_TOKEN" ]]; then
            echo "✓ Secret loaded successfully"
            echo "✓ Integration test passed"
          else
            echo "⨯ Failed to load secret"
            exit 1
          fi
