name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
      
      - name: Load secret
        id: load-secret
        uses: 1password/load-secrets-action@v1
        # Reference secret using the item UUID
        with:
          secrets: |
            API_TOKEN = op://Development Credentials/bqye3bjuhjxqf6meco4tleije/credential
            
      - name: Test secret
        run: |
          echo "Testing 1Password secret access..."
          if [[ -n "${{ steps.load-secret.outputs.API_TOKEN }}" ]]; then
            echo "✓ Secret loaded successfully"
          else
            echo "⨯ Failed to load secret"
            exit 1
          fi
