name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Check 1Password connection
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        run: |
          echo "Checking 1Password connection..."
          if op vault list; then
            echo "✓ Successfully connected to 1Password"
            echo "Available vaults:"
            op vault list
          else
            echo "⨯ Failed to connect to 1Password"
            exit 1
          fi

      - name: Load secret
        uses: 1password/load-secrets-action@v1
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        with:
          export-env: true
          secret-files: |
            GITHUB_TOKEN="Development Credentials"/"Service Account Auth Token: GitHub Actions"/.credential

      - name: Verify secret
        run: |
          if [[ -n "$GITHUB_TOKEN" ]]; then
            echo "✓ Secret loaded successfully"
          else
            echo "⨯ Failed to load secret"
            exit 1
          fi
