name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Debug 1Password Configuration
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        run: |
          echo "1Password CLI Version: $(op --version)"
          echo "Checking vault access..."
          op vault list --format=json || true
          echo "Checking item access..."
          op item list --vault="Development Credentials" || true

      - name: Load secrets
        uses: 1password/load-secrets-action@v1
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        with:
          # Using direct reference from op item list
          secrets: |
            TOKEN="Service Account Auth Token: GitHub Actions"

      - name: Test loaded secret
        run: |
          echo "Testing loaded secret..."
          if [[ -n "$TOKEN" ]]; then
            echo "✓ Secret loaded successfully"
          else
            echo "⨯ Failed to load secret"
            echo "Available environment variables:"
            env | grep -v "SECRET" | grep -v "TOKEN"
            exit 1
          fi
