name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Load secrets from 1Password
        uses: 1password/load-secrets-action@v1
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        with:
          export-env: false
          # List of secrets to load
          secrets: |
            TEST_SECRET=Development Credentials/Service Account Auth Token: GitHub Actions

      - name: Test connection
        run: |
          echo "Testing 1Password connection..."
          if op account list > /dev/null 2>&1; then
            echo "✓ Successfully connected to 1Password"
          else
            echo "⨯ Failed to connect to 1Password"
            exit 1
          fi

      - name: Verify secret
        env:
          TEST_SECRET: ${{ env.TEST_SECRET }}
        run: |
          if [[ -n "$TEST_SECRET" ]]; then
            echo "✓ Secret loaded successfully"
          else
            echo "⨯ Failed to load secret"
            exit 1
          fi
