name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Load 1Password secrets
        uses: 1password/load-secrets-action@v1
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        with:
          # Export secrets to environment variables
          export-env: false
          # Define secrets to load
          secrets: GH_TOKEN=op://Development Credentials/Service Account Auth Token: GitHub Actions/credential

      - name: Debug secret loading
        env:
          GH_TOKEN: ${{ env.GH_TOKEN }}
        run: |
          echo "Checking 1Password CLI..."
          op --version
          
          echo -e "\nChecking loaded secret..."
          if [[ -n "${GH_TOKEN}" ]]; then
            echo "✓ Secret loaded successfully"
            echo "✓ Integration test passed"
          else
            echo "⨯ Failed to load secret"
            echo "Environment context:"
            echo "OP_MANAGED_VARIABLES: $OP_MANAGED_VARIABLES"
            exit 1
          fi
