name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Inspect 1Password Configuration
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        run: |
          echo "1Password CLI version:"
          op --version
          
          echo -e "\nListing accounts:"
          op account list || true
          
          echo -e "\nListing vaults:"
          op vault list --format=json || true
          
          echo -e "\nListing items in Development Credentials vault:"
          op item list --vault="Development Credentials" --format=json || true
          
          echo -e "\nAttempting to get specific item:"
          op item get "Service Account Auth Token: GitHub Actions" \
            --vault="Development Credentials" \
            --format=json || true

      - name: Load Secret (Simple)
        uses: 1password/load-secrets-action@v1
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        with:
          export-env: true
          secrets: |
            AUTH_TOKEN="Development Credentials/Service Account Auth Token: GitHub Actions"

      - name: Verify Secret
        run: |
          echo "Checking loaded secret..."
          if [[ -n "$AUTH_TOKEN" ]]; then
            echo "✓ Secret loaded successfully"
          else
            echo "⨯ Failed to load secret"
            exit 1
          fi
