name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Load secrets
        id: op-load-secret
        uses: 1password/load-secrets-action@v1
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        with:
          secrets: |
            MY_SECRET=Development Credentials/Service Account Auth Token: GitHub Actions/credential

      - name: Test secret
        run: |
          echo "Testing secret from outputs..."
          if [[ -n "${{ steps.op-load-secret.outputs.MY_SECRET }}" ]]; then
            echo "✓ Secret loaded successfully"
          else
            echo "⨯ Failed to load secret"
            exit 1
          fi
