name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
      
      - name: Load 1Password Secrets
        uses: 1password/load-secrets-action@v1
        with:
          # Export secrets to environment
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          # Reference secrets using the op:// protocol
          TOKEN: op://Development Credentials/Service Account Auth Token: GitHub Actions/credential
          
      - name: Verify 1Password Integration
        run: |
          echo "Testing 1Password integration..."
          if [ -n "$TOKEN" ]; then
            echo "✓ Successfully loaded secret from 1Password"
            echo "✓ Integration test passed"
          else
            echo "⨯ Failed to load secret from 1Password"
            exit 1
          fi
