name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1 # v1 is fine for install

      - name: Load secrets
        uses: 1password/load-secrets-action@v2 # Using v2 as per docs
        with:
          export-env: true # Export to environment variables
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          # Define the secret to load and the env var name
          LOADED_GITHUB_TOKEN: "op://Development Credentials/Service Account Auth Token: GitHub Actions/credential"

      - name: Test secret access
        run: |
          echo "Checking loaded secret..."
          if [[ -n "$LOADED_GITHUB_TOKEN" ]]; then
            echo "✓ Secret loaded successfully into LOADED_GITHUB_TOKEN"
            echo "Value starts with: ${LOADED_GITHUB_TOKEN:0:10}..." # Print first 10 chars for verification, GitHub will mask it
            echo "Testing GitHub API access..."
            if curl -s -H "Authorization: token $LOADED_GITHUB_TOKEN" https://api.github.com/user > /dev/null; then
              echo "✓ GitHub token is valid and API call successful"
              echo "✓ Integration test passed"
            else
              echo "⨯ GitHub token validation failed with API call"
              exit 1
            fi
          else
            echo "⨯ Failed to load secret into LOADED_GITHUB_TOKEN"
            echo "Debug info:"
            echo "1Password CLI version: $(op --version)"
            op vault list || true
            exit 1
          fi
