name: 1Password Integration Test

on:
  repository_dispatch:
    types: [test-1password]
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Load secrets from 1Password
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GITHUB_TOKEN: op://Development Credentials/Service Account Auth Token: GitHub Actions/credential
          
      - name: Verify 1Password secrets
        run: |
          echo "Testing 1Password integration..."
          if [ -n "$GITHUB_TOKEN" ]; then
            echo "✓ 1Password GitHub Actions integration successful"
          else
            echo "⨯ Failed to load secrets"
            exit 1
          fi
