name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Load Secrets
        uses: 1password/load-secrets-action@v1
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        with:
          # Export secrets as environment variables
          export-env: true
          # Load the secret using environment variables format
          load-env: |
            AUTH_TOKEN=op://Development Credentials/bqye3bjuhjxqxf6meco4tleije/credential

      - name: Verify Secret
        if: success()
        run: |
          echo "Checking loaded secret..."
          if [[ -n "$AUTH_TOKEN" ]]; then
            echo "✓ Secret loaded successfully"
            echo "✓ Integration test passed"
          else
            echo "⨯ Failed to load secret"
            echo "Debug: Checking environment variables:"
            printenv | grep -v "TOKEN" | grep -v "SECRET"
            exit 1
          fi
