name: 1Password 3rd Party Auth Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Load API tokens from 1Password
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GITHUB_PAT: "op://Development Credentials/GitHub Personal Access Token/token"
          GCP_JSON_KEY: "op://Development Credentials/GCP Service Account Key/json"
          SCIM_BEARER: "op://Development Credentials/1Password SCIMsession Bearer Token/credential"

      - name: Show masked secret variable presence
        run: |
          echo "GitHub PAT present: $([[ -n \"$GITHUB_PAT\" ]] && echo yes || echo no)"
          echo "GCP Service Account JSON present: $([[ -n \"$GCP_JSON_KEY\" ]] && echo yes || echo no)"
          echo "SCIM Bearer Token present: $([[ -n \"$SCIM_BEARER\" ]] && echo yes || echo no)"

      - name: Test GitHub token
        run: |
          if [[ -n "$GITHUB_PAT" ]]; then
            echo "Testing GitHub API authentication..."
            if curl -Sfs -H "Authorization: token $GITHUB_PAT" https://api.github.com/user > /dev/null; then
              echo "✓ GitHub PAT authentication successful."
            else
              echo "⨯ GitHub PAT authentication failed."
              exit 1
            fi
          else
            echo "⨯ GitHub PAT not set."
            exit 1
          fi

      - name: Test 1Password Bearer Token (SCIM)
        run: |
          if [[ -n "$SCIM_BEARER" ]]; then
            echo "SCIM Bearer Token loaded (value is masked)."
            # Insert API call here to your 1Password SCIM API endpoint using $SCIM_BEARER
            echo "✓ SCIM Bearer Token available."
          else
            echo "⨯ SCIM Bearer Token not set."
            exit 1
          fi

      # Add additional 3rd party service token tests as needed here.
