name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
      
      - name: Load 1Password Secrets
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          # Using exact item reference from vault
          SERVICE_ACCOUNT_TOKEN: "op://Development Credentials/Service Account Auth Token: GitHub Actions/credential"
          
      - name: Debug Secret Access
        run: |
          echo "1Password CLI Version:"
          op --version
          echo -e "\nVerifying vault access:"
          op vault list
          echo -e "\nTesting secret access:"
          if [ -n "$SERVICE_ACCOUNT_TOKEN" ]; then
            echo "✓ Service account token loaded successfully"
          else
            echo "⨯ Failed to load service account token"
            exit 1
          fi
