name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Configure 1Password CLI
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        run: |
          echo "Testing 1Password CLI configuration..."
          if op vault list > /dev/null 2>&1; then
            echo "✓ 1Password CLI configured successfully"
            op vault list
          else
            echo "⨯ Failed to configure 1Password CLI"
            exit 1
          fi

      - name: Load secret
        uses: 1password/load-secrets-action@v1
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        with:
          export-env: true
          secrets: |
            TEST_SECRET=op://Development Credentials/Service Account Auth Token: GitHub Actions/credential

      - name: Verify secret
        run: |
          echo "Verifying secret..."
          if [[ -n "$TEST_SECRET" ]]; then
            echo "✓ Secret loaded successfully"
          else
            echo "⨯ Failed to load secret"
            echo "Available environment variables:"
            env | grep -v "TOKEN" | grep -v "SECRET"
            exit 1
          fi
