name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Load secrets
        uses: 1password/load-secrets-action@v1
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        with:
          # Mark as non-exported
          export-env: false
          # Load secrets in reference format
          secrets: |
            GITHUB_TOKEN=Development Credentials/Service Account Auth Token: GitHub Actions/credential

      - name: Test secret access
        if: success()
        run: |
          echo "Checking loaded secret..."
          if [[ -n "$GITHUB_TOKEN" ]]; then
            echo "✓ Secret loaded successfully"
            # Simple test of token validity
            if curl -s -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/user > /dev/null; then
              echo "✓ GitHub token is valid"
            else
              echo "⨯ GitHub token validation failed"
              exit 1
            fi
          else
            echo "⨯ Failed to load secret"
            echo "OP_MANAGED_VARIABLES: $OP_MANAGED_VARIABLES"
            exit 1
          fi
