name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Load secrets
        uses: 1password/load-secrets-action@v1
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        with:
          export-env: true
          secrets: |
            GITHUB_TOKEN=op://4zmavkpsr4kueyredsceutw554/bqye3bjuhjxqxf6meco4tleije/credential

      - name: Test loaded secrets
        run: |
          echo "Checking secret loading status..."
          if [[ -n "$GITHUB_TOKEN" ]]; then
            echo "✓ Secret loaded successfully"
            echo "✓ Integration test passed"
          else
            echo "⨯ Failed to load secret"
            echo "Available environment variables:"
            env | grep -v "TOKEN" | grep -v "SECRET"
            exit 1
          fi
