name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
        
      - name: Debug Environment
        run: |
          echo "Current working directory: $(pwd)"
          echo "GitHub workspace: $GITHUB_WORKSPACE"
          echo "1Password CLI version: $(op --version)"
      
      - name: Load 1Password Secrets
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SERVICE_ACCOUNT_TOKEN: op://Development Credentials/bqye3bjuhjxqxf6meco4tleije/credential
          
      - name: Verify Secret Access
        run: |
          echo "Checking environment setup..."
          if [ -n "$OP_SERVICE_ACCOUNT_TOKEN" ]; then
            echo "✓ Service account token is set"
          else
            echo "⨯ Service account token is missing"
            exit 1
          fi
          
          echo "Verifying secret access..."
          if [ -n "$SERVICE_ACCOUNT_TOKEN" ]; then
            echo "✓ Successfully loaded secret from 1Password"
            echo "✓ Integration test passed"
          else
            echo "⨯ Failed to load secret"
            exit 1
          fi
