name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
      
      - name: Load 1Password Secrets
        uses: 1password/load-secrets-action@v1
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          
      - name: Read Service Account Token
        run: |
          echo "Testing 1Password CLI..."
          op item get "Service Account Auth Token: GitHub Actions" --vault "Development Credentials" --format json > token.json
          if [ -f "token.json" ]; then
            echo "✓ Successfully connected to 1Password"
            rm token.json
          else
            echo "⨯ Failed to connect to 1Password"
            exit 1
          fi
