name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Check 1Password configuration
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        run: |
          echo "Testing 1Password configuration..."
          if op account get --format=json; then
            echo "✓ Service account configured"
            op vault list
          else
            echo "⨯ Service account configuration failed"
            exit 1
          fi

      - name: Load secrets
        uses: 1password/load-secrets-action@v1
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        with:
          export-env: true
          secrets: |
            AUTH_TOKEN="op://Development Credentials/bqye3bjuhjxqxf6meco4tleije/credential"

      - name: Verify secrets
        if: success()
        run: |
          if [[ -n "$AUTH_TOKEN" ]]; then
            echo "✓ Secret loaded successfully"
          else
            echo "⨯ Failed to load secret"
            echo "Debug: Checking available vaults..."
            op vault list || true
            exit 1
          fi
