name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Load Secrets
        uses: 1password/load-secrets-action@v1
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        with:
          # List of secrets to load
          secrets: |
            SECRET_TOKEN = op://Development Credentials/Service Account Auth Token: GitHub Actions/credential

      - name: Debug Environment
        if: always()
        run: |
          echo "Checking 1Password CLI version:"
          op --version
          echo "Checking environment variables (excluding sensitive data):"
          env | grep -v "TOKEN" | grep -v "SECRET"
          
      - name: Test Loaded Secret
        shell: bash
        run: |
          if [[ -n "$SECRET_TOKEN" ]]; then
            echo "✓ Secret loaded successfully"
          else
            echo "⨯ Failed to load secret"
            echo "Debug: Attempting to list available secrets..."
            op item list --vault "Development Credentials" || true
            exit 1
          fi
