# 1Password GitHub Actions Integration Test
name: 1Password Integration Test

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master

jobs:
  test-1password:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Load secrets from 1Password
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GITHUB_TOKEN: op://Development Credentials/Service Account Auth Token: GitHub Actions/credential
          
      - name: Verify 1Password secrets
        run: |
          if [ -n "$GITHUB_TOKEN" ]; then
            echo "✓ 1Password GitHub Actions integration successful"
            echo "✓ Service account token loaded correctly"
          else
            echo "⨯ Failed to load secrets"
            exit 1
          fi
