name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Load secrets
        uses: 1password/load-secrets-action@v1
        with:
          # Using the format from documentation
          secrets: |
            TEST_SECRET=4zmavkpsr4kueyredsceutw554/bqye3bjuhjxqxf6meco4tleije/credential

      - name: Test secret
        env:
          TEST_SECRET: ${{ steps.load-secrets.outputs.TEST_SECRET }}
        run: |
          echo "Checking loaded secret..."
          if [[ -n "${TEST_SECRET}" ]]; then
            echo "✓ Secret loaded successfully"
            echo "✓ Integration test passed"
          else
            echo "⨯ Failed to load secret"
            echo "Debug information:"
            echo "1Password CLI version: $(op --version)"
            env | grep -v "SECRET" | grep -v "TOKEN"
            exit 1
          fi
