name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Load secrets
        id: load-secrets
        uses: 1password/load-secrets-action@v1
        with:
          # Export secrets to environment variables
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GITHUB_ACCESS_TOKEN: "op://Development Credentials/Service Account Auth Token: GitHub Actions/credential"

      - name: Test secret access
        env:
          LOADED_TOKEN: ${{ steps.load-secrets.outputs.GITHUB_ACCESS_TOKEN }}
        run: |
          echo "Checking secret access..."
          if [[ -n "$LOADED_TOKEN" ]]; then
            echo "✓ Successfully loaded secret"
            echo "Testing GitHub API access..."
            curl -H "Authorization: token $LOADED_TOKEN" \
                 -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/user
          else
            echo "⨯ Failed to load secret"
            exit 1
          fi
