name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Load secrets
        id: op-secrets
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          # Using UUIDs for vault and item
          LOADED_GITHUB_TOKEN: "op://4zmavkpsr4kueyredsceutw554/bqye3bjuhjxqxf6meco4tleije/credential"

      - name: Test secret access
        run: |
          echo "Checking loaded secret (LOADED_GITHUB_TOKEN)..."
          if [[ -n "$LOADED_GITHUB_TOKEN" ]]; then
            echo "✓ LOADED_GITHUB_TOKEN is populated."
            echo "Value starts with: ${LOADED_GITHUB_TOKEN:0:5}..."
            
            echo "Testing GitHub API access with the loaded token..."
            if curl -Sfs -H "Authorization: token $LOADED_GITHUB_TOKEN" https://api.github.com/user > /dev/null; then
              echo "✓ GitHub token is valid and API call successful."
              echo "✓ Integration test passed."
            else
              echo "⨯ GitHub API call failed with the loaded token."
              exit 1
            fi
          else
            echo "⨯ Failed to load secret into LOADED_GITHUB_TOKEN."
            exit 1
          fi
