name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Configure Service Account
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        run: |
          echo "Configuring 1Password service account..."
          op account list || true
          echo "Testing vault access..."
          if op item list --vault="Development Credentials"; then
            echo "✓ Successfully accessed Development Credentials vault"
          else
            echo "⨯ Failed to access vault"
            exit 1
          fi

      - name: Load Secret
        uses: 1password/load-secrets-action@v1
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        with:
          # Using direct item reference for Codespaces compatibility
          export-env: true
          secrets: |
            GITHUB_TOKEN=op://Development Credentials/Service Account Auth Token: GitHub Actions/credential

      - name: Verify Secret
        run: |
          echo "Checking loaded secret..."
          if [[ -n "$GITHUB_TOKEN" ]]; then
            echo "✓ Secret loaded successfully"
            echo "Testing GitHub authentication with token..."
            # Test the token works with GitHub API
            if curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user > /dev/null; then
              echo "✓ GitHub token is valid"
            else
              echo "⨯ GitHub token validation failed"
              exit 1
            fi
          else
            echo "⨯ Failed to load secret"
            exit 1
          fi
