name: 1Password Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-1password:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
      
      - name: Load secret
        id: load-secret
        uses: 1password/load-secrets-action@v1
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        with:
          # Export secrets to environment variables
          export-env: true
          # Define secrets to load in 1Password connect format
          secrets: |
            TOKEN="op://Development Credentials/Service Account Auth Token: GitHub Actions/credential"
            
      - name: Test secret
        run: |
          echo "Testing 1Password secret access..."
          if [[ -n "${{ steps.load-secret.outputs.TOKEN }}" ]]; then
            echo "✓ Secret loaded successfully from outputs"
            echo "✓ Integration test passed"
          elif [[ -n "$TOKEN" ]]; then
            echo "✓ Secret loaded successfully from environment"
            echo "✓ Integration test passed"
          else
            echo "⨯ Failed to load secret"
            echo "Available environment variables:"
            env | grep -v "OP_SERVICE_ACCOUNT_TOKEN"
            exit 1
          fi
